# Topic modeling + Doc2Vec on LinkedIn job postings

## Overview

In this notebook, I apply unsupervised learning techniques to discover hidden patterns in a [LinkedIn job postings dataset from KaggleHub.

To do this I:
1. Preprocess a corpus using spaCy tokenization, lemmatization, and stop word removal.
2. Build a Gensim Dictionary and convert documents into Bag-of-Words and TF-IDF representations.
3. Apply Latent Dirichlet Allocation (LDA) to discover topic clusters.
4. Build a matching system using both TF-IDF cosine similarity and Doc2Vec embeddings.
5. Explore semantic relationships using pre-trained GloVe word embeddings.

#### Dataset

[LinkedIn Job Postings dataset](https://www.kaggle.com/datasets/arshkon/linkedin-job-postings) contains job descriptions and other data from various postings.

*Arsh Koneru. (2024). LinkedIn Job Postings (2023 - 2024) [Data set]. Kaggle. https://doi.org/10.34740/KAGGLE/DSV/9200871*

In [ ]:
!pip install gensim -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 59.1 MB/s eta 0:00:00

In [1]:
import random
import textwrap

import numpy as np
import pandas as pd
import spacy

import kagglehub

import gensim
import gensim.downloader as api
from gensim import corpora
from gensim import models
from gensim import similarities
from gensim.models import doc2vec

ModuleNotFoundError: No module named 'gensim'

In [ ]:
# set random seed
seed = 42
# Load spacy small english language model
nlp = spacy.load("en_core_web_sm")

### Download and Convert to DataFrame

Load the dataset and, if necessary, convert it to a Pandas DataFrame.

In [ ]:
directory = kagglehub.dataset_download("arshkon/linkedin-job-postings")
directory

Downloading to /root/.cache/kagglehub/datasets/arshkon/linkedin-job-postings/13.archive...

100%|██████████| 159M/159M [00:01<00:00, 115MB/s]

Extracting files...

'/root/.cache/kagglehub/datasets/arshkon/linkedin-job-postings/versions/13'

In [ ]:
# Read dataset into pandas
file_path = f"{directory}/postings.csv"
df = pd.read_csv(file_path)
df.shape

(123849, 31)

In [ ]:
# Inspect the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  object
 2   title                       123849 non-null  object
 3   description                 123842 non-null  object
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   object
 6   location                    123849 non-null  object
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  object
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              15246 non-null   float64
 15  job_posting_url             123849 non-null  object
 16  application_url             87184 non-null   object
 17  application_type            123849 non-null  object
 18  expiry                      123849 non-null  float64
 19  closed_time                 1073 non-null    float64
 20  formatted_experience_level  94440 non-null   object
 21  skills_desc                 2439 non-null    object
 22  listed_time                 123849 non-null  float64
 23  posting_domain              83881 non-null   object
 24  sponsored                   123849 non-null  int64
 25  work_type                   123849 non-null  object
 26  currency                    36073 non-null   object
 27  compensation_type           36073 non-null   object
 28  normalized_salary           36073 non-null   float64
 29  zip_code                    102977 non-null  float64
 30  fips                        96434 non-null   float64
dtypes: float64(14), int64(2), object(15)
memory usage: 29.3+ MB

In [ ]:
df.describe()

,job_id,max_salary,company_id,views,med_salary,min_salary,applies,original_listed_time,remote_allowed,expiry,closed_time,listed_time,sponsored,normalized_salary,zip_code,fips
count,1.238490e+05,2.979300e+04,1.221320e+05,122160.000000,6280.000000,2.979300e+04,23320.000000,1.238490e+05,15246.0,1.238490e+05,1.073000e+03,1.238490e+05,123849.0,3.607300e+04,102977.000000,96434.000000
mean,3.896402e+09,9.193942e+04,1.220401e+07,14.618247,22015.619876,6.491085e+04,10.591981,1.713152e+12,1.0,1.716213e+12,1.712928e+12,1.713204e+12,0.0,2.053270e+05,50400.491887,28713.879887
std,8.404355e+07,7.011101e+05,2.554143e+07,85.903598,52255.873846,4.959738e+05,29.047395,4.848209e+08,0.0,2.321394e+09,3.622893e+08,3.989122e+08,0.0,5.097627e+06,30252.232515,16015.929825
min,9.217160e+05,1.000000e+00,1.009000e+03,1.000000,0.000000,1.000000e+00,1.000000,1.701811e+12,1.0,1.712903e+12,1.712346e+12,1.711317e+12,0.0,0.000000e+00,1001.000000,1003.000000
25%,3.894587e+09,4.828000e+01,1.435200e+04,3.000000,18.940000,3.700000e+01,1.000000,1.712863e+12,1.0,1.715481e+12,1.712670e+12,1.712886e+12,0.0,5.200000e+04,24112.000000,13121.000000
50%,3.901998e+09,8.000000e+04,2.269650e+05,4.000000,25.500000,6.000000e+04,3.000000,1.713395e+12,1.0,1.716042e+12,1.712670e+12,1.713408e+12,0.0,8.150000e+04,48059.000000,29183.000000
75%,3.904707e+09,1.400000e+05,8.047188e+06,8.000000,2510.500000,1.000000e+05,8.000000,1.713478e+12,1.0,1.716088e+12,1.713283e+12,1.713484e+12,0.0,1.250000e+05,78201.000000,42077.000000
max,3.906267e+09,1.200000e+08,1.034730e+08,9975.000000,750000.000000,8.500000e+07,967.000000,1.713573e+12,1.0,1.729125e+12,1.713562e+12,1.713573e+12,0.0,5.356000e+08,99901.000000,56045.000000

In [ ]:
df[15:20]

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
15,83789755,OsteoStrong,Osteogenic Loading Coach,"Company DescriptionOsteoStrong® is not a gym, ...",NaN,NaN,"Anchorage, AK",3810432.0,4.0,NaN,...,NaN,1.713466e+12,NaN,0,FULL_TIME,NaN,NaN,NaN,99501.0,2020.0
16,95428182,CLEVELAND KIDS BOOK BANK,Administrative Coordinator,Job Title: Administrative CoordinatorOrganizat...,NaN,HOURLY,"Cleveland, OH",55624331.0,1.0,25.0,...,NaN,1.712856e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,52000.0,44102.0,39035.0
17,103860943,NaN,Customer Service / Reservationist,Sentinel Limousine of East Providence RI is a ...,19.0,HOURLY,"Providence, RI",NaN,3.0,NaN,...,NaN,1.713532e+12,NaN,0,PART_TIME,USD,BASE_SALARY,38480.0,2903.0,44007.0
18,111513530,United Methodists of Greater New Jersey,"Content Writer, Communications","Application opening date: April 24, 2024\nTitl...",NaN,NaN,Greater Philadelphia,4028816.0,10.0,NaN,...,NaN,1.713457e+12,NaN,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN
19,115639136,Shannon Waltchack,Controller,WORK @ SWShannon Waltchack (SW) is seeking a C...,NaN,NaN,"Birmingham, AL",988555.0,61.0,NaN,...,Strong interpersonal communication skills and ...,1.713210e+12,NaN,0,FULL_TIME,NaN,NaN,NaN,35203.0,1073.0

### Sample the Dataset

I sample 3000 rows from the dataset

In [ ]:
data_sample = df.sample(n=3000,random_state=42).reset_index(drop=True)

## Data Preparation and Preprocessing

In [ ]:
# Extract primary text column "description" from Job Postings dataset
#.. stored as a list of documents using .tolist()
job_descriptions = data_sample["description"].tolist()

### Preprocessing with spaCy

Tokenizer function is defined that processes text using spaCy. The function does the following:
- Removes punctuation
- Removes stop words
- Removes non-alphabetic tokens (numbers, special characters)
- Removes named entities (companies)
- Returns the lemmatized form of the remaining tokens

Note: named entities are removed so that companies that post multiple (non-identical) jobs are not mistakenly grouped together, given that we want to group by actual job roles (i.e. skills, responsibilities, etc.)

In [ ]:
# Tokenizer
def spacy_tokenizer(text: str) -> list[str]:
    doc = nlp(text.lower())
    return  [token.lemma_ for token in doc if token.is_alpha and token.ent_iob_ == "O"
        and not token.is_stop and len(token.lemma_) > 2]

In [ ]:
# Apply Tokenizer to all docs (job_descriptions)
# just apply documents to it in list comprehension (not a specific module)

processed_docs = [spacy_tokenizer(job) for job in job_descriptions]
processed_docs

[['senior',
  'automation',
  'power',
  'system',
  'engineer',
  'primarily',
  'responsible',
  'conception',
  'design',
  'development',
  'implementation',
  'electrical',
  'system',
  'candidate',
  'extensive',
  'knowledge',
  'electrical',
  'power',
  'system',
  'active',
  'end',
  'afe',
  'system',
  'plc',
  'programming',
  'experience',
  'candidate',
  'possess',
  'ability',
  'apply',
  'mathematical',
  'engineering',
  'principle',
  'detailed',
  'description',
  'responsible',
  'design',
  'develop',
  'electrical',
  'system',
  'include',
  'generator',
  'control',
  'switchboards',
  'drive',
  'active',
  'end',
  'afe',
  'motor',
  'control',
  'system',
  'panel',
  'board',
  'component',
  'require',
  'function',
  'system',
  'accord',
  'customer',
  'power',
  'system',
  'simulation',
  'analysis',
  'engineering',
  'complex',
  'power',
  'system',
  'microgrid',
  'large',
  'analyze',
  'harmonic',
  'corrective',
  'measure',
  'complex',
  'power',
  'systemsexperience',
  'specify',
  'design',
  'implement',
  'active',
  'end',
  'afe',
  'system',
  'multiple',
  'generator',
  'system',
  'non',
  'utility',
  'analyze',
  'rationalize',
  'power',
  'system',
  'quality',
  'metric',
  'theoretical',
  'experimental',
  'approach',
  'theory',
  'match',
  'actual',
  'system',
  'performance',
  'yes',
  'designing',
  'implement',
  'commission',
  'multiple',
  'generator',
  'system',
  'isolated',
  'gridprovide',
  'continue',
  'support',
  'project',
  'completion',
  'field',
  'commission',
  'phone',
  'form',
  'troubleshooting',
  'person',
  'onsite',
  'require',
  'job',
  'requirement',
  'ability',
  'work',
  'independently',
  'team',
  'manage',
  'multiple',
  'task',
  'work',
  'multiple',
  'project',
  'simultaneously',
  'meet',
  'challenge',
  'clear',
  'write',
  'verbal',
  'communication',
  'skill',
  'ability',
  'promptly',
  'follow',
  'direction',
  'work',
  'navigate',
  'work',
  'site',
  'include',
  'regular',
  'walking',
  'climbing',
  'standing',
  'stepping',
  'etc',
  'weather',
  'condition',
  'day',
  'night',
  'outdoor',
  'hot',
  'cold',
  'use',
  'office',
  'suite',
  'develop',
  'presentation',
  'correspondence',
  'report',
  'schedule',
  'word',
  'excel',
  'power',
  'point',
  'carry',
  'independently',
  'walk',
  'uneven',
  'surfacesbend',
  'stoop',
  'kneel',
  'twist',
  'crawl',
  'occasionally',
  'visit',
  'field',
  'operational',
  'work',
  'unusual',
  'noise',
  'signify',
  'equipment',
  'machinery',
  'alert',
  'focus',
  'include',
  'occasional',
  'extend',
  'work',
  'spatial',
  'orientation',
  'awareness',
  'safely',
  'work',
  'environment',
  'moving',
  'object',
  'include',
  'overhead',
  'personal',
  'protective',
  'equipment',
  'ppe',
  'designate',
  'regularly',
  'travel',
  'need',
  'visit',
  'work',
  'site',
  'support',
  'business',
  'unit',
  'require',
  'extended',
  'travel',
  'remote',
  'location',
  'overnight',
  'outside',
  'normal',
  'office',
  'work',
  'weekend',
  'need',
  'minimum',
  'qualificationsdegree',
  'relate',
  'electrical',
  'engineering',
  'prove',
  'experience',
  'electrical',
  'system',
  'afe',
  'drive',
  'standard',
  'field',
  'bus',
  'communication',
  'protocol',
  'ethernet',
  'profinet',
  'canbus',
  'opc',
  'autocad',
  'electrical',
  'preferred',
  'qualification',
  'prove',
  'experience',
  'electrical',
  'system',
  'design',
  'level',
  'electrical',
  'engineering',
  'degreeproven',
  'experience',
  'vfd',
  'drive',
  'afe',
  'drive',
  'system',
  'preferably',
  'experience',
  'multiple',
  'generator',
  'power',
  'system',
  'design',
  'simulation',
  'analysis',
  'commissioning',
  'field',
  'supportproven',
  'experience',
  'equipment',
  'drilling',
  'marine',
  'mining',
  'industry',
  'additional',
  'detail',
  'work',
  'primarily',
  'climate',
  'control',
  'office',
  'environment',
  'minimal',
  'safety',
  'health',
  'hazard',
  'potential',
  'employee',
  'regularly',
  'require',
  'sit',
  'stand',
  'walk',
  'occasional',
  'lifting',
  'overhead',
  'waist',
  'level',
  'floor',
  'bend',
  'frequent',
  'near',
  'vision',
  'use',
  'reading',
  'use',
  'computer',
  'telephone',
  'office',
  'equipment',
  'employee',
  'work',
  'emphasis',
  'safety',
  'include',
  'coworker',
  'party',
  'include',
  'wear',
  'require',
  'personal',
  'protective',
  'equipment',
  'ppe',
  'designate',
  'time',
  'position',
  'require',
  'employee',
  'work',
  'shop',
  'environment',
  'field',
  'base',
  'location',
  'type',
  'weather',
  'condition',
  'typical',
  'area',
  'job',
  'locate',
  'include',
  'dust',
  'humidity',
  'sleet',
  'snow',
  'rain',
  'mud',
  'cold',
  'heat',
  'wind',
  'inclement',
  'weather',
  'work',
  'condition',
  'position',
  'involve',
  'exposure',
  'vary',
  'outdoor',
  'condition',
  'include',
  'environmental',
  'chemical',
  'gas',
  'noise',
  'dampness',
  'fume',
  'radiation',
  'height'],
 ['company',
  'summary',
  'dish',
  'echostar',
  'company',
  'reimagine',
  'future',
  'connectivity',
  'business',
  'reach',
  'span',
  'satellite',
  'television',
  'service',
  'live',
  'streaming',
  'demand',
  'programming',
  'smart',
  'home',
  'installation',
  'service',
  'mobile',
  'plan',
  'product',
  'build',
  'smart',
  'network',
  'brand',
  'include',
  'echostar',
  'hughe',
  'dish',
  'sling',
  'boost',
  'infinite',
  'boost',
  'mobile',
  'dish',
  'wireless',
  'ontech',
  'genmobile',
  'department',
  'summary',
  'technician',
  'deliver',
  'smart',
  'home',
  'solution',
  'customer',
  'technician',
  'train',
  'lead',
  'charge',
  'world',
  'class',
  'customer',
  'experience',
  'educate',
  'connect',
  'home',
  'visit',
  'backbone',
  'organization',
  'ensure',
  'excellent',
  'customer',
  'experience',
  'dedication',
  'customer',
  'experience',
  'pay',
  'dish',
  'earn',
  'power',
  'award',
  'overall',
  'customer',
  'satisfaction',
  'job',
  'duty',
  'responsibility',
  'guarantee',
  'promotion',
  'hour',
  'pay',
  'increase',
  'performance',
  'incentive',
  'potential',
  'follow',
  'training',
  'pay',
  'time',
  'pay',
  'day',
  'work',
  'opportunity',
  'work',
  'overtimemedical',
  'dental',
  'vision',
  'life',
  'insurance',
  'package',
  'health',
  'saving',
  'dish',
  'programming',
  'value',
  'month',
  'home',
  'plus',
  'deeply',
  'discount',
  'sling',
  'boost',
  'infinite',
  'phone',
  'company',
  'stock',
  'purchasing',
  'program',
  'reimbursementdish',
  'supply',
  'tool',
  'uniform',
  'great',
  'benefit',
  'opportunity',
  'current',
  'leadership',
  'start',
  'technician',
  'grit',
  'tenacity',
  'grow',
  'quickly',
  'dish',
  'performance',
  'base',
  'promotion',
  'include',
  'automatic',
  'pay',
  'increase',
  'level',
  'level',
  'field',
  'technician',
  'represent',
  'dish',
  'customer',
  'home',
  'build',
  'value',
  'simplify',
  'life',
  'dish',
  'install',
  'consult',
  'homeowner',
  'infinite',
  'smart',
  'home',
  'possibility',
  'skill',
  'experience',
  'requirement',
  'technician',
  'aptitude',
  'build',
  'rapport',
  'quickly',
  'want',
  'great',
  'time',
  'service',
  'clientsability',
  'work',
  'height',
  'include',
  'ladder',
  'weather',
  'conditionsability',
  'lift',
  'lbsa',
  'valid',
  'driver',
  'license',
  'state',
  'seek',
  'employment',
  'driving',
  'record',
  'meet',
  'dish',
  'safety',
  'standardtravel',
  'require',
  'salary',
  'range',
  'compensation',
  'hour',
  'benefit',
  'versatile',
  'health',
  'perk',
  'new',
  'career',
  'opportunity',
  'check',
  'benefit',
  'career',
  'website',
  'employment',
  'contingent',
  'successful',
  'completion',
  'pre',
  'employment',
  'screen',
  'include',
  'drug',
  'test',
  'acceptable',
  'driving',
  'record',
  'compensation',
  'list',
  'reflect',
  'combination',
  'pay',
  'rate',
  'location',
  'pay',
  'differential',
  'post',
  'minimum',
  'position',
  'fill'],
 ['division',
  'north',
  'alabama',
  'department',
  'oxford',
  'warehouse',
  'loading',
  'work',
  'schedule',
  'finish',
  'love',
  'coca',
  'cola',
  'united',
  'privately',
  'own',
  'operate',
  'historical',
  'strength',
  'stabilitydedicate',
  'support',
  'internal',
  'career',
  'growth',
  'job',
  'training',
  'learning',
  'opportunity',
  'career',
  'advancementexcellent',
  'total',
  'value',
  'benefit',
  'package',
  'include',
  'pay',
  'vacation',
  'yearcomprehensive',
  'medical',
  'preferred',
  'provider',
  'plan',
  'physical',
  'copay',
  'teladoc',
  'vision',
  'flex',
  'spendingemployee',
  'assistance',
  'programcompany',
  'pay',
  'life',
  'insurance',
  'optional',
  'insurance',
  'accident',
  'critical',
  'illness',
  'universal',
  'life',
  'home',
  'maternity',
  'paternity',
  'leavepaid',
  'holiday',
  'sick',
  'match',
  'plus',
  'additional',
  'annual',
  'match',
  'employee',
  'discount',
  'cell',
  'phone',
  'event',
  'ticket',
  'gym',
  'membership',
  'car',
  'buying',
  'hotel',
  'car',
  'rental',
  'technology',
  'need',
  'compensation',
  'fast',
  'pace',
  'environment',
  'promote',
  'healthy',
  'lifestylefor',
  'qualified',
  'candidate',
  'offer',
  'amazing',
  'cdl',
  'tuition',
  'program',
  'reimbursable',
  'cdl',
  'school',
  'tuition',
  'ask',
  'recruiter',
  'detail',
  'job',
  'description',
  'material',
  'handler',
  'loader',
  'responsible',
  'fill',
  'customer',
  'order',
  'ticket',
  'voice',
  'perform',
  'follow',
  'duty',
  'day',
  'look',
  'like',
  'fill',
  'order',
  'ticket',
  'accord',
  'set',
  'quotasorder',
  'fill',
  'manually',
  'walk',
  'use',
  'pallet',
  'rid',
  'jacksidentify',
  'product',
  'description',
  'quantity',
  'remove',
  'product',
  'area',
  'carry',
  'staging',
  'areacheck',
  'accuracy',
  'pickinggeneral',
  'power',
  'equipment',
  'inspection',
  'formread',
  'customer',
  'order',
  'work',
  'order',
  'shipping',
  'order',
  'requisition',
  'determine',
  'item',
  'move',
  'gather',
  'distributedsort',
  'place',
  'material',
  'item',
  'pallet',
  'accord',
  'predetermine',
  'sequence',
  'size',
  'type',
  'product',
  'codemark',
  'material',
  'identify',
  'informationrecord',
  'amount',
  'material',
  'item',
  'receive',
  'distributedcount',
  'item',
  'distribution',
  'plant',
  'ensure',
  'conformance',
  'company',
  'standardsperform',
  'appropriate',
  'duty',
  'assign',
  'management',
  'need',
  'succeed',
  'minimum',
  'age',
  'oldpersonal',
  'protective',
  'equipment',
  'ppe',
  'require',
  'position',
  'compliance',
  'united',
  'safety',
  'policiesregular',
  'prompt',
  'attendance',
  'essential',
  'function',
  'jobability',
  'read',
  'write',
  'speak',
  'englishability',
  'maintain',
  'neat',
  'professional',
  'appearance',
  'company',
  'guidelinesability',
  'maintain',
  'safety',
  'security',
  'company',
  'assetsability',
  'utilize',
  'company',
  'provide',
  'resource',
  'technologyless',
  'high',
  'school',
  'education',
  'related',
  'experience',
  'training',
  'equivalent',
  'combination',
  'education',
  'experienceforklift',
  'electric',
  'riding',
  'pallet',
  'jack',
  'experience',
  'preferredrepeatedly',
  'graspingcontinuous',
  'standing',
  'walk',
  'bending',
  'kneeling',
  'squatting',
  'push',
  'pull',
  'frequent',
  'lifting',
  'carry',
  'push',
  'pull',
  'effectively',
  'adapt',
  'changeability',
  'demonstrate',
  'initiativeability',
  'work',
  'safely',
  'securelywillingness',
  'work',
  'weekend',
  'holiday',
  'flexible',
  'schedule',
  'require',
  'ccbcu',
  'equal',
  'opportunity',
  'employer',
  'minority',
  'woman',
  'veteran',
  'disabled',
  'veteran',
  'friendly'],
 ['kmgh',
  'affiliate',
  'look',
  'multimedia',
  'journalist',
  'live',
  'work',
  'beautiful',
  'mountain',
  'community',
  'entry',
  'level',
  'position',
  'role',
  'perfect',
  'truly',
  'love',
  'solo',
  'storytelling',
  'look',
  'right',
  'backdrop',
  'ideal',
  'candidate',
  'curious',
  'meet',
  'new',
  'people',
  'find',
  'story',
  'important',
  'job',
  'variety',
  'cover',
  'challenge',
  'affordable',
  'housing',
  'ski',
  'community',
  'wildfire',
  'preparedness',
  'amazing',
  'outdoor',
  'recreation',
  'offer',
  'primarily',
  'work',
  'independently',
  'opportunity',
  'visit',
  'newsroom',
  'collaborate',
  'train',
  'leadership',
  'colleague',
  'team',
  'photojournalist',
  'break',
  'news',
  'receive',
  'assignment',
  'evaluate',
  'news',
  'lead',
  'news',
  'tip',
  'develop',
  'story',
  'verify',
  'factual',
  'information',
  'story',
  'interview',
  'observation',
  'material',
  'determine',
  'slant',
  'emphasis',
  'write',
  'story',
  'accord',
  'prescribe',
  'editorial',
  'style',
  'format',
  'video',
  'photo',
  'illustrate',
  'assist',
  'editing',
  'video',
  'multimedia',
  'package',
  'live',
  'site',
  'event',
  'mobile',
  'broadcast',
  'cooperatively',
  'photographer',
  'assign',
  'story',
  'news',
  'producer',
  'prepare',
  'online',
  'staff',
  'prepare',
  'multimedia',
  'write',
  'capture',
  'quality',
  'visual',
  'content',
  'edit',
  'produce',
  'story',
  'multiple',
  'platform',
  'deadline',
  'internet',
  'digital',
  'channel',
  'need',
  'bachelor',
  'degree',
  'broadcast',
  'journalism',
  'related',
  'degree',
  'equivalent',
  'experience',
  'related',
  'field',
  'prefer',
  'bring',
  'computer',
  'literacy',
  'require',
  'include',
  'newsroom',
  'computer',
  'non',
  'linear',
  'editing',
  'experience',
  'broadcast',
  'quality',
  'camera',
  'video',
  'final',
  'cut',
  'pro',
  'editing',
  'system',
  'similar',
  'broadcast',
  'style',
  'writing',
  'post',
  'content',
  'motivated',
  'able',
  'work',
  'fast',
  'pace',
  'deadline',
  'drive',
  'able',
  'lift',
  'driver',
  'license',
  'good',
  'driving',
  'record',
  'require',
  'addition',
  'proof',
  'insurance',
  'liability',
  'coverage',
  'require',
  'compensation',
  'range',
  'annual',
  'salary',
  'pursuant',
  'state',
  'local',
  'salary',
  'transparency',
  'law',
  'salary',
  'range',
  'post',
  'specific',
  'candidate',
  'perform',
  'work',
  'offer',
  'additional',
  'benefit',
  'career',
  'path',
  'grow',
  'professional',
  'experiencesfull',
  'medical',
  'dental',
  'vision',
  'benefit',
  'certain',
  'health',
  'wellness',
  'benefitsretirement',
  'saving',
  'plan',
  'company',
  'matchother',
  'key',
  'company',
  'benefit',
  'include',
  'disability',
  'accident',
  'insurance',
  'hospital',
  'indemnity',
  'critical',
  'illness',
  'life',
  'insurance',
  'protection',
  'pet',
  'discount',
  'program',
  'employee',
  'assistance',
  'program',
  'detail',
  'timing',
  'condition',
  'benefit',
  'eligibility',
  'plan',
  'term',
  'condition',
  'provide',
  'hire',
  'current',
  'employee',
  'apply',
  'site',
  'access',
  'internal',
  'career',
  'site',
  'worklife',
  'info',
  'view',
  'open',
  'position',
  'scripp',
  'scripp',
  'commitment',
  'equity',
  'diversity',
  'inclusion',
  'scripps',
  'commit',
  'diverse',
  'inclusive',
  'culture',
  'reflect',
  'community',
  'serve',
  'intentional',
  'create',
  'environment',
  'employee',
  'audience',
  'stakeholder',
  'feel',
  'value',
  'inspire',
  'reach',
  'potential',
  'authentic',
  'connection',
  'foster',
  'workplace',
  'culture',
  'embrace',
  'person',
  'diversity',
  'include',
  'extent',
  'similar',
  'different',
  'scripps',
  'leader',
  'believe',
  'equitable',
  'inclusive',
  'culture',
  'right',
  'thing',
  'business',
  'imperative',
  'read',
  'commitment',
  'equity',
  'diversity',
  'inclusion',
  'scripp',
  'scripps',
  'company',
  'nasdaq',
  'ssp',
  'diversified',
  'medium',
  'company',
  'focus',
  'create',
  'well',
  'inform',
  'world',
  'nation',
  'large',
  'local',
  'broadcaster',
  'serve',
  'community',
  'quality',
  'objective',
  'local',
  'journalism',
  'operate',
  'portfolio',
  'station',
  'market',
  'scripps',
  'reach',
  'household',
  'national',
  'news',
  'outlet',
  'scripps',
  'news',
  'court',
  'popular',
  'entertainment',
  'brand',
  'ion',
  'bounce',
  'defy',
  'grit',
  'ion',
  'mystery',
  'laff',
  'nation',
  'large',
  'holder',
  'broadcast',
  'spectrum',
  'longtime',
  'steward',
  'found',
  'scripps',
  'long',
  'time',
  'motto',
  'light',
  'people',
  'find',
  'way',
  'equal',
  'employment',
  'opportunity',
  'employer',
  'affiliate',
  'discriminate',
  'employment',
  'decision',
  'basis',
  'race',
  'sex',
  'sexual',
  'orientation',
  'transgender',
  'status',
  'gender',
  'color',
  'religion',
  'age',
  'genetic',
  'information',
  'medical',
  'condition',
  'disability',
  'marital',
  'status',
  'citizenship',
  'national',
  'origin',
  'military',
  'membership',
  'veteran',
  'status',
  'basis',
  'violation',
  'applicable',
  'federal',
  'state',
  'local',
  'law',
  'furthermore',
  'company',
  'reasonable',
  'accommodation',
  'qualified',
  'individual',
  'know',
  'disability',
  'result',
  'undue',
  'hardship',
  'company'],
 ['come',
  'flexibility',
  'stay',
  'culture',
  'need',
  'life',
  'work',
  'life',
  'balance',
  'apply',
  'talent',
  'network',
  'bayada',
  'offer',
  'lpns',
  'careflexible',
  'scheduling',
  'base',
  'preferencesweekly',
  'paypreventive',
  'care',
  'coverage',
  'employee',
  'prn',
  'commute',
  'time',
  'match',
  'case',
  'nearest',
  'youmedical',
  'dental',
  'vision',
  'benefitscompany',
  'pay',
  'life',
  'insuranceemployee',
  'assistance',
  'advancement',
  'training',
  'bayada',
  'home',
  'health',
  'care',
  'found',
  'principle',
  'health',
  'care',
  'get',
  'well',
  'client',
  'well',
  'care',
  'home',
  'place',
  'want',
  'deliver',
  'care',
  'high',
  'priority',
  'great',
  'joy',
  'prepare',
  'lpns',
  'success',
  'pay',
  'training',
  'office',
  'home',
  'onlinepractice',
  'award',
  'win',
  'adult',
  'pediatric',
  'simulation',
  'labsaround',
  'clock',
  'clinical',
  'support',
  'phoneelectronic',
  'charting',
  'alayacare',
  'care',
  'client',
  'age',
  'diagnosis',
  'acuity',
  'level',
  'offer',
  'multitude',
  'pay',
  'training',
  'nurse',
  'feel',
  'comfortable',
  'competent',
  'shift',
  'available',
  'lpn',
  'shift',
  'shiftweekday',
  'weekend',
  'requirement',
  'current',
  'valid',
  'nursing',
  'license',
  'qualified',
  'nursing',
  'program',
  'pay',
  'hour',
  'apply',
  'join',
  'team',
  'ner',
  'accredit',
  'regulate',
  'certify',
  'license',
  'home',
  'health',
  'care',
  'provider',
  'bayada',
  'complie',
  'state',
  'local',
  'mandate',
  'bayada',
  'home',
  'health',
  'care',
  'inc',
  'associate',
  'entity',
  'joint',
  'venture',
  'partner',
  'equal',
  'opportunity',
  'employer',
  'employment',
  'decision',
  'non',
  'discriminatory',
  'basis',
  'regard',
  'sex',
  'race',
  'color',
  'age',
  'disability',
  'pregnancy',
  'maternity',
  'sexual',
  'orientation',
  'gender',
  'identity',
  'citizenship',
  'status',
  'military',
  'status',
  'similarly',
  'protect',
  'status',
  'accordance',
  'federal',
  'state',
  'local',
  'law',
  'strongly',
  'encourage',
  'application',
  'people',
  'identity',
  'member',
  'marginalized',
  'community'],
 ['hybrid',
  'roleonsite',
  'require',
  'work',
  'onsite',
  'office',
  'week',
  'busy',
  'period',
  'week',
  'depend',
  'workload',
  'have',
  'yoe',

---

## Vectorization with TF-IDF

### Creating a Gensim Dictionary

Here a Gensim `Dictionary` is built from the processed documents. The dictionary maps every unique token to a unique integer ID, which allows for efficient representation of Gensim corpora.

In [ ]:
# can access like normal python dictionary (except keys are id)
docs_dict = corpora.Dictionary(processed_docs)

In [ ]:
# Job Postings dataset
for i in range(20):
  print(f"id: {i}: {docs_dict[i]}")

id: 0: ability
id: 1: accord
id: 2: active
id: 3: actual
id: 4: additional
id: 5: afe
id: 6: alert
id: 7: analysis
id: 8: analyze
id: 9: apply
id: 10: approach
id: 11: area
id: 12: autocad
id: 13: automation
id: 14: awareness
id: 15: base
id: 16: bend
id: 17: board
id: 18: bus
id: 19: business

### Filtering Extremes

Words that appear in fewer than 2 documents or more than %50 of the documents are removed.

In [ ]:
# gensim: dictName.filter_extremes(no_below=,no_above=)
docs_dict.filter_extremes(no_below=2, no_above=0.5)

### Creating Bag-of-Words Corpus

Processed documents are converted to a Bag-of-Words representation using the filtered dictionary.

In [ ]:
bow_corpus = [docs_dict.doc2bow(doc) for doc in processed_docs]
len(bow_corpus)

3000

### Generating TF-IDF Vectors

TF-IDF model is created from the Bag-of-Words corpus.

In [ ]:
# models.TfidfModel(corpusHere)
tfidf_model = models.TfidfModel(bow_corpus)

In [ ]:
# model is applied to the corpus to create TF-IDF
tfidf_corpus = tfidf_model[bow_corpus] #tfidf_model[] is triggering Gensim's __getitem__ method

---

## Topic Modeling with LDA

### Training the LDA Model

An LDA (Latent Dirichlet Allocation) model is trained on the TF-IDF corpus to discover latent clusters.

In [ ]:
# originally tried num_topics=10, passes=20 this didn't produce coherent results
# next tried 20 topics & 30 passes
# next tried 30 topics & 30 passes
lda_model = models.LdaModel(corpus=tfidf_corpus, id2word=docs_dict, num_topics=30, passes=30, random_state=42)

### Extracting Topic Keywords

Below the top 10 keywords for each discovered topic are displayed.

In [ ]:
lda_model.print_topics(num_topics=30, num_words=10)

[(0,
  '0.015*"skf" + 0.007*"specimen" + 0.006*"fedex" + 0.005*"autism" + 0.005*"nordstrom" + 0.004*"napa" + 0.004*"ace" + 0.004*"mom" + 0.003*"aba" + 0.003*"seattle"'),
 (1,
  '0.011*"galt" + 0.010*"credit" + 0.007*"sale" + 0.007*"figure" + 0.007*"earning" + 0.007*"saas" + 0.007*"owner" + 0.006*"personal" + 0.006*"membership" + 0.005*"careerstaff"'),
 (2,
  '0.012*"trading" + 0.005*"trader" + 0.004*"ios" + 0.003*"thrivework" + 0.002*"eci" + 0.002*"pcu" + 0.002*"altame" + 0.002*"massage" + 0.002*"quantitative" + 0.002*"hydro"'),
 (3,
  '0.011*"beauty" + 0.007*"trailer" + 0.006*"ulta" + 0.006*"bakery" + 0.005*"req" + 0.005*"tradesman" + 0.003*"hair" + 0.003*"street" + 0.003*"foodservice" + 0.003*"datadog"'),
 (4,
  '0.006*"leasing" + 0.004*"associatesassist" + 0.004*"bayada" + 0.002*"delta" + 0.002*"pierce" + 0.002*"tpm" + 0.002*"gate" + 0.002*"csat" + 0.002*"westside" + 0.002*"mcc"'),
 (5,
  '0.007*"hardware" + 0.006*"coordinator" + 0.006*"chain" + 0.006*"logistic" + 0.005*"troubleshoot" + 0.005*"procurement" + 0.004*"attorney" + 0.004*"civil" + 0.004*"feature" + 0.004*"sql"'),
 (6,
  '0.003*"scm" + 0.003*"tile" + 0.003*"hygienist" + 0.002*"optometrist" + 0.002*"clin" + 0.002*"arrow" + 0.002*"optometry" + 0.001*"ppc" + 0.001*"hallmark" + 0.001*"stone"'),
 (7,
  '0.007*"dentist" + 0.005*"android" + 0.005*"cad" + 0.005*"script" + 0.005*"subcontractor" + 0.005*"receivable" + 0.005*"scrum" + 0.004*"dentistry" + 0.004*"semiconductor" + 0.004*"unix"'),
 (8,
  '0.009*"solomon" + 0.009*"ultrasound" + 0.005*"tiktok" + 0.004*"page" + 0.004*"locum" + 0.003*"manpowergroup" + 0.003*"amerigas" + 0.003*"modernization" + 0.003*"propane" + 0.003*"remodeling"'),
 (9,
  '0.014*"cogent" + 0.007*"mortgage" + 0.006*"fpga" + 0.004*"wsp" + 0.003*"photo" + 0.003*"thrivent" + 0.003*"mercyone" + 0.003*"loan" + 0.003*"rehab" + 0.003*"vaccination"'),
 (10,
  '0.008*"psychiatric" + 0.006*"chef" + 0.006*"est" + 0.006*"ehs" + 0.006*"instructional" + 0.004*"interim" + 0.004*"wfm" + 0.004*"carousel" + 0.004*"marvin" + 0.004*"substance"'),
 (11,
  '0.007*"radiologic" + 0.006*"pct" + 0.005*"roofing" + 0.005*"davita" + 0.005*"dialysis" + 0.004*"baxter" + 0.003*"cheese" + 0.003*"renal" + 0.003*"brief" + 0.003*"interventional"'),
 (12,
  '0.006*"pipe" + 0.004*"poverty" + 0.003*"tennis" + 0.003*"tenant" + 0.003*"cis" + 0.003*"borgen" + 0.003*"metronet" + 0.003*"fiber" + 0.002*"ice" + 0.002*"xcel"'),
 (13,
  '0.007*"apex" + 0.007*"amergis" + 0.006*"albertson" + 0.006*"lion" + 0.006*"maxim" + 0.006*"cox" + 0.005*"westrock" + 0.005*"chipotle" + 0.004*"cnc" + 0.003*"franchisee"'),
 (14,
  '0.007*"actalent" + 0.006*"deli" + 0.006*"securita" + 0.006*"securitas" + 0.005*"bjc" + 0.005*"vigilance" + 0.004*"helpfulness" + 0.004*"honeywell" + 0.003*"var" + 0.003*"asm"'),
 (15,
  '0.006*"autozone" + 0.004*"que" + 0.003*"hyatt" + 0.003*"fun" + 0.003*"dish" + 0.003*"waist" + 0.003*"habit" + 0.003*"suggestion" + 0.003*"cane" + 0.003*"crewmember"'),
 (16,
  '0.006*"liberty" + 0.006*"lpn" + 0.006*"nursing" + 0.004*"wind" + 0.004*"geriatric" + 0.004*"nurse" + 0.004*"stride" + 0.004*"hall" + 0.003*"notifying" + 0.003*"otis"'),
 (17,
  '0.015*"macy" + 0.012*"penske" + 0.009*"trinity" + 0.009*"pvh" + 0.007*"providence" + 0.006*"receptionist" + 0.006*"clerical" + 0.006*"caci" + 0.004*"betterhelp" + 0.004*"logistics"'),
 (18,
  '0.009*"mercy" + 0.006*"dice" + 0.004*"devsecop" + 0.004*"snowflake" + 0.003*"exhibitor" + 0.003*"nyc" + 0.003*"gene" + 0.002*"sandy" + 0.002*"ministry" + 0.002*"ryder"'),
 (19,
  '0.006*"hca" + 0.003*"methodist" + 0.003*"biofire" + 0.003*"bmc" + 0.003*"pharmacist" + 0.003*"wash" + 0.003*"carbon" + 0.002*"telecommunications" + 0.002*"surg" + 0.002*"donor"'),
 (20,
  '0.010*"capital" + 0.009*"agent" + 0.006*"chatbot" + 0.006*"stryker" + 0.006*"teksystem" + 0.004*"refrigeration" + 0.004*"claire" + 0.004*"mount" + 0.004*"tray" + 0.004*"paypal"'),
 (21,
  '0.004*"aldi" + 0.004*"reinsurance" + 0.004*"msl" + 0.003*"correctional" + 0.003*"ride" + 0.003*"unitypoint" + 0.003*"dar" + 0.002*"professor" + 0.002*"jail" + 0.002*"asbestos"'),
 (22,
  '0.008*"cinta" + 0.006*"ecommerce" + 0.005*"app" + 0.005*"venue" + 0.004*"shelter" + 0.004*"kid" + 0.004*"consolidated" + 0.004*"armstaffe" + 0.003*"scripting" + 0.003*"topgolf"'),
 (23,
  '0.004*"patient" + 0.003*"sale" + 0.003*"customer" + 0.003*"care" + 0.003*"project" + 0.003*"client" + 0.003*"store" + 0.002*"product" + 0.002*"business" + 0.002*"design"'),
 (24,
  '0.006*"speech" + 0.005*"aaa" + 0.004*"langone" + 0.004*"cisco" + 0.004*"bluebird" + 0.004*"pathology" + 0.002*"stipend" + 0.002*"pathologist" + 0.002*"cls" + 0.002*"weekson"'),
 (25,
  '0.010*"collision" + 0.009*"caliber" + 0.004*"rpm" + 0.004*"tesla" + 0.003*"staffmark" + 0.003*"graph" + 0.003*"signature" + 0.003*"grooming" + 0.002*"aetna" + 0.002*"maplewood"'),
 (26,
  '0.005*"rail" + 0.004*"cha" + 0.003*"helpdesk" + 0.003*"flyer" + 0.002*"hcm" + 0.002*"revature" + 0.002*"traction" + 0.001*"fieldexperience" + 0.001*"laurel" + 0.001*"tommy"'),
 (27,
  '0.005*"alcon" + 0.005*"substation" + 0.004*"bsa" + 0.004*"gaming" + 0.004*"meta" + 0.004*"sage" + 0.003*"powerback" + 0.003*"shrm" + 0.003*"aml" + 0.003*"creator"'),
 (28,
  '0.010*"hospice" + 0.007*"block" + 0.006*"fire" + 0.005*"counselor" + 0.005*"universal" + 0.005*"united" + 0.004*"citi" + 0.004*"dod" + 0.004*"county" + 0.004*"examination"'),
 (29,
  '0.005*"diy" + 0.005*"salesperson" + 0.005*"medpro" + 0.002*"wiper" + 0.002*"moines" + 0.002*"skillsoperate" + 0.002*"des" + 0.002*"medline" + 0.002*"out" + 0.002*"expose"')]

---

## Document Retrieval

In this section, I implement a query-based document retrieval system using two different approaches:
1. TF-IDF with cosine similarity (exact word overlap, weighted by rarity)
2. Doc2Vec embeddings (semantic meaning, capturing conceptual similarity)

The query created consists of 10 specific terms that represent a target subset of the documents in the dataset. I'm generally testing for jobs pertaining to: *Language Engineer, Data Linguist, Data Language Scientist, NLP Linguist, Machine Learning Language Scientist*, etc.

In [ ]:
query = [
    "python",
    "data",
    "engineer",
    "language",
    "learning",
    "stack",
    "database",
    "algorythm",
    "program",
    "machine"
]


# Vectorize query same as done for query the original documents
query_bow = docs_dict.doc2bow(query)

In [ ]:
# TF-IDF
# Use the `MatrixSimilarity` class to calculate cosine similarity between vectors.
query_tfidf = tfidf_model[query_bow]

In [ ]:
# Calculate the similarities of all documents to query.
index_tfidf = similarities.MatrixSimilarity(tfidf_corpus)
sims_tfidf = index_tfidf[query_tfidf] # results in np array of scores

WARNING:gensim.similarities.docsim:scanning corpus to determine the number of features (consider setting `num_features` explicitly)

In [ ]:
# Display the top 3 most similar documents based on TF-IDF similarity.
sorted_sims_tfidf = sorted(enumerate(sims_tfidf), key=lambda sim: -sim[1])

for rank in range(3):
  doc_index = sorted_sims_tfidf[rank][0]
  sim_score = sorted_sims_tfidf[rank][1]
  print(f"\n\nRank {rank + 1} (Score: {sim_score:.4f}):")
  print("\n".join(textwrap.wrap(job_descriptions[doc_index])))

Rank 1 (Score: 0.4036):
One of our Fortune 100 clients in Plano, TX is looking for a Full
Stack Data Engineer/Developer.   Title: Full Stack Data Engineer /
DeveloperLocation: Plano, TX (Fri – Remote)Hourly: $70 per hour
(W2)Duration: 1 year (Contract-to-Hire)  Stack Experience:Minimum 5
years of Full Stack expertise in one of the following stacks and
comfortable exploring othersMERN stack: JavaScript - MongoDB - Express
- ReactJS - Node.js (Preferred)MEAN stack: JavaScript - MongoDB -
Express - AngularJS - Node.jsLAMP stack: JavaScript - Linux - Apache -
MySQL – PHPLEMP stack: JavaScript - Linux - Nginx - MySQL – PHPDjango
stack: JavaScript - Python - Django – MySQLRuby on Rails: JavaScript -
Ruby - SQLite – Rails   Must-to-Have:Git URL(Required)Minimum 5 years
of experience with Data Modeling in Big Data environment and have
worked on massive structured/unstructured datasets beforeBig Data
stack (Hadoop, Hive, Spark, Kafka, Airflow/OOZIE,
BigQuery/Presto/Impala etc.)Experience working in AWS/GCP/Azure cloud
environmentsServer programming using NodeJS, Python, PHP, ASPDatabase
programming using SQL, SQLite, Hive/Hadoop, or MongoDBExperienced in
APIs and Micro services development and managementProficient in
object-oriented language – Python/Scala preferredExpert in networking
concepts and security protocolsSolid understanding of containerized
platforms (Docker, Kubernetes)Experience using GIT, JIRA, and
Confluence tools  Job ResponsibilitiesDesign, develop, test, deploy,
maintain and enhance our desktop-based data web applications from
front-end to back-end.Triage product and system issues and
debug/resolve by analyzing the source of issues and impact on service
operations and qualityCollaborate with product managers, data
engineers, data analysts, and marketing tech vendors to prioritize
engineering deadlines and deliverablesWork with data engineers and
data scientists to design and deploy complex data models, fueling the
applicationDeploy applications on cloud infrastructure, ensuring
scalability, performance, and securityIntegrate application with in-
house big data system and third-party marketing systems using APIs and
other solutionsWrite clean, efficient, and reusable code and
contribute to existing documentation and adapt content based on
product/program updates and user feedbackStay updated on emerging web
application and data modeling technologies and integrate with the
product where applicableWork with product managers, data scientists,
and engineers to understand business goals and data science and
marketing tech stack of the company  Core Qualifications:Curious,
ownership, and outcome mindset with the ability to pivot as per
business requirementsBachelor’s degree in Computer Science,
Engineering, or related fieldYou have interest to grow your knowledge
in the area of Data Science and willing to lend a hand in “Machine
Learning” application development when requiredComfortable with Agile
Principles/Scrum/KanbanExperience developing products for marketing
and sales teams in Omni-channel organizations, small or large


Rank 2 (Score: 0.2914):
Data Engineer - Remote - Competitive Salary + Bonus + Benefits
DescriptionWe are looking for a skilled Data Engineer to join our
established client on a remote basis. As a Data Engineer, you will be
responsible for developing and maintaining the data infrastructure of
our organization. You will work closely with our data scientists,
software engineers, and other stakeholders to ensure the smooth flow
and storage of data. In this role, you will play a critical part in
designing, implementing, and managing the entire data pipeline, from
data ingestion to data transformation and storage. You will be
responsible for developing and maintaining scalable and efficient data
pipelines, ensuring data quality and integrity, and optimizing data
workflows. Additionally, you will collaborate with cross-functional
teams to gather data requirements and provide technical expertise on
data-related projects. ResponsibilitiesDevelop, maintain, and optimize
data pipelines to ensure efficient data ingestion, transformation, and
storage.Implement and manage data modeling and schema design to
support data analytics and reporting requirements.Collaborate with
data scientists and software engineers to implement machine learning
models and algorithms into production systems.Monitor and troubleshoot
data pipelines to identify and resolve data quality issues or
performance bottlenecks.Implement and maintain data governance
policies, data security measures, and data privacy
regulations.Collaborate with stakeholders to gather data requirements
and provide technical recommendations on data-related projects.Stay
up-to-date with the latest trends and technologies in data engineering
and apply them to enhance data infrastructure and workflows.
RequirementsBachelor's degree in Computer Science, Information
Systems, or a related field.Proven experience as a Data Engineer or
similar role, with a strong understanding of data engineering concepts
and best practices.Proficient in programming languages such as Python
or Java, and experience working with SQL and NoSQL
databases.Experience with data warehousing concepts, ETL processes,
and cloud-based data platforms (e.g., AWS, GCP, or Azure).Strong
understanding of data modeling techniques, data structures, and
algorithms.Familiarity with data governance frameworks, data security
measures, and data privacy regulations.Excellent problem-solving and
analytical skills, with the ability to identify and troubleshoot data-
related issues.Strong communication skills and the ability to
collaborate effectively with cross-functional teams.


Rank 3 (Score: 0.2914):
Data Engineer - Remote - Competitive Salary + Bonus + Benefits
DescriptionWe are looking for a skilled Data Engineer to join our
established client on a remote basis. As a Data Engineer, you will be
responsible for developing and maintaining the data infrastructure of
our organization. You will work closely with our data scientists,
software engineers, and other stakeholders to ensure the smooth flow
and storage of data. In this role, you will play a critical part in
designing, implementing, and managing the entire data pipeline, from
data ingestion to data transformation and storage. You will be
responsible for developing and maintaining scalable and efficient data
pipelines, ensuring data quality and integrity, and optimizing data
workflows. Additionally, you will collaborate with cross-functional
teams to gather data requirements and provide technical expertise on
data-related projects. ResponsibilitiesDevelop, maintain, and optimize
data pipelines to ensure efficient data ingestion, transformation, and
storage.Implement and manage data modeling and schema design to
support data analytics and reporting requirements.Collaborate with
data scientists and software engineers to implement machine learning
models and algorithms into production systems.Monitor and troubleshoot
data pipelines to identify and resolve data quality issues or
performance bottlenecks.Implement and maintain data governance
policies, data security measures, and data privacy
regulations.Collaborate with stakeholders to gather data requirements
and provide technical recommendations on data-related projects.Stay
up-to-date with the latest trends and technologies in data engineering
and apply them to enhance data infrastructure and workflows.
RequirementsBachelor's degree in Computer Science, Information
Systems, or a related field.Proven experience as a Data Engineer or
similar role, with a strong understanding of data engineering concepts
and best practices.Proficient in programming languages such as Python
or Java, and experience working with SQL and NoSQL
databases.Experience with data warehousing concepts, ETL processes,
and cloud-based data platforms (e.g., AWS, GCP, or Azure).Strong
understanding of data modeling techniques, data structures, and
algorithms.Familiarity with data governance frameworks, data security
measures, and data privacy regulations.Excellent problem-solving and
analytical skills, with the ability to identify and troubleshoot data-
related issues.Strong communication skills and the ability to
collaborate effectively with cross-functional teams.

### Matching via Doc2Vec

Next, query matches are found using **Doc2Vec** embeddings which captures semantic meaning, allowing it to find documents that are conceptually similar even if they use different vocabulary.

In [ ]:
tagged_docs = [doc2vec.TaggedDocument(words=doc, tags=[str(i)]) for i, doc in enumerate(processed_docs)]
len(tagged_docs)

3000

Doc2Vec model instantiated with the following parameters:
- `vector_size`: Dimensionality of the feature vectors (embeddings). Larger vectors can capture more nuance but require more training data.
- `min_count`: Ignores all words with total frequency lower than this value.
- `epochs`: Number of iterations over the corpus to use for training.

In [ ]:
d2v_model = doc2vec.Doc2Vec(vector_size=50, min_count=2, epochs=40)

In [ ]:
# build vocabulary for Doc2Vec
d2v_model.build_vocab(tagged_docs)

In [ ]:
# Display the first 20 words in the vocabulary by their index.
for i in range(20):
    print(f"ID: {i:2} | Word: {d2v_model.wv.index_to_key[i]}")

ID:  0 | Word: work
ID:  1 | Word: experience
ID:  2 | Word: team
ID:  3 | Word: include
ID:  4 | Word: customer
ID:  5 | Word: service
ID:  6 | Word: require
ID:  7 | Word: job
ID:  8 | Word: provide
ID:  9 | Word: skill
ID: 10 | Word: opportunity
ID: 11 | Word: business
ID: 12 | Word: company
ID: 13 | Word: support
ID: 14 | Word: time
ID: 15 | Word: ability
ID: 16 | Word: employee
ID: 17 | Word: management
ID: 18 | Word: position
ID: 19 | Word: need

In [ ]:
# Note to self: Check what are epochs..
d2v_model.train(tagged_docs, total_examples=d2v_model.corpus_count, epochs=d2v_model.epochs)

In [ ]:
# vector representation calculated for query
query_vec = d2v_model.infer_vector(query)
#print(query_vec)

Next, using the trained model the top 3 most similar documents are displayed

In [ ]:
sims_d2v = d2v_model.dv.most_similar([query_vec], topn=3)
# Doc2Vec (sims_d2v) returns a list of (string, float) tuples:
print(sims_d2v)

for rank, (tag, sim_score) in enumerate(sims_d2v[:3]):
  doc_index = int(tag)
  print(f"\n\nRank {rank + 1} (Score: {sim_score:.4f})")
  print(f"\n".join(textwrap.wrap(job_descriptions[doc_index])))

[('2933', 0.6148601174354553), ('1593', 0.5975397825241089), ('858', 0.5906465649604797)]


Rank 1 (Score: 0.6149)
One of our Fortune 100 clients in Plano, TX is looking for a Full
Stack Data Engineer/Developer.   Title: Full Stack Data Engineer /
DeveloperLocation: Plano, TX (Fri – Remote)Hourly: $70 per hour
(W2)Duration: 1 year (Contract-to-Hire)  Stack Experience:Minimum 5
years of Full Stack expertise in one of the following stacks and
comfortable exploring othersMERN stack: JavaScript - MongoDB - Express
- ReactJS - Node.js (Preferred)MEAN stack: JavaScript - MongoDB -
Express - AngularJS - Node.jsLAMP stack: JavaScript - Linux - Apache -
MySQL – PHPLEMP stack: JavaScript - Linux - Nginx - MySQL – PHPDjango
stack: JavaScript - Python - Django – MySQLRuby on Rails: JavaScript -
Ruby - SQLite – Rails   Must-to-Have:Git URL(Required)Minimum 5 years
of experience with Data Modeling in Big Data environment and have
worked on massive structured/unstructured datasets beforeBig Data
stack (Hadoop, Hive, Spark, Kafka, Airflow/OOZIE,
BigQuery/Presto/Impala etc.)Experience working in AWS/GCP/Azure cloud
environmentsServer programming using NodeJS, Python, PHP, ASPDatabase
programming using SQL, SQLite, Hive/Hadoop, or MongoDBExperienced in
APIs and Micro services development and managementProficient in
object-oriented language – Python/Scala preferredExpert in networking
concepts and security protocolsSolid understanding of containerized
platforms (Docker, Kubernetes)Experience using GIT, JIRA, and
Confluence tools  Job ResponsibilitiesDesign, develop, test, deploy,
maintain and enhance our desktop-based data web applications from
front-end to back-end.Triage product and system issues and
debug/resolve by analyzing the source of issues and impact on service
operations and qualityCollaborate with product managers, data
engineers, data analysts, and marketing tech vendors to prioritize
engineering deadlines and deliverablesWork with data engineers and
data scientists to design and deploy complex data models, fueling the
applicationDeploy applications on cloud infrastructure, ensuring
scalability, performance, and securityIntegrate application with in-
house big data system and third-party marketing systems using APIs and
other solutionsWrite clean, efficient, and reusable code and
contribute to existing documentation and adapt content based on
product/program updates and user feedbackStay updated on emerging web
application and data modeling technologies and integrate with the
product where applicableWork with product managers, data scientists,
and engineers to understand business goals and data science and
marketing tech stack of the company  Core Qualifications:Curious,
ownership, and outcome mindset with the ability to pivot as per
business requirementsBachelor’s degree in Computer Science,
Engineering, or related fieldYou have interest to grow your knowledge
in the area of Data Science and willing to lend a hand in “Machine
Learning” application development when requiredComfortable with Agile
Principles/Scrum/KanbanExperience developing products for marketing
and sales teams in Omni-channel organizations, small or large


Rank 2 (Score: 0.5975)
Title: Data Engineer Location: San Diego, CA This is a contract
position on W2 only. Job Description: Data engineer to design, process
for and build automation for test data analytics and data
structure.Engineer is also responsible for injecting domain knowledge
into Knowledge Graph (graph database) and supporting execution of an
analytic workflow modeled through a Knowledge Graph.  Top 5 Required
Skills: 5 years or more experience with the following languages:
Python, Java Script, C#, Shell scripting2 years or more experience
with databases PostgreSQL: querying (SQL), and data modeling.1 year or
more experience with graph data models and graph databasesExperience
with web development framework especially Rest API and
ORM.Semiconductor knowledge in Product and Test EngineeringExperience
in developing data science solution for Hardware Engineering  Required
Education: Bachelor degree in Computer/Electrical Engineering,
Math/Stats, Computer Science, or related field. with 2 years of
experience-OR- Masters Degree in Computer/Electrical Engineering,
Math/Stats, Computer Science, or related field. with 1 years of
experience


Rank 3 (Score: 0.5906)
Job Description  In the hardware development of platforms for the data
center business of Intel, you will routinely learn and apply board
development fundamentals which involve qualifying PCB implementation
through measurement and validation. As an intern, working on a signal
integrity team, you will develop new/existing tools to increase
automation and organization of measured data.  In this process, you
will continuously interact with other engineers and stakeholders
across several groups to accomplish high quality results for our
platforms and customers.  The Ideal Candidate Should Exhibit The
Following Behavioral Traits  Strong leadership and results oriented
behavior.Excellent written and verbal communication skillsWilling to
collaborate with others constructively.Works well independently and
develops quick engineering solutions for problems.  Qualifications
Qualifications  Candidate must possess the minimum qualifications to
be initially considered for this position. Preferred qualifications
are in addition to the minimum qualifications and are considered a
plus factor in identifying top candidates. Relevant experience can be
obtained through schoolwork, classes, projects, internships, military
training, and/or work experience.  Minimum Qualifications  Candidate
must have a bachelor’s degree in Computer Science, Computer
Engineering or Electrical Engineering and should be actively pursuing
a graduate degree.  Preferred Qualifications  6 months+ of background
in computer science fundamentals and application  Python, Java, C,
C++, others  Electrical engineering and computer architecture basics
Experience in computer science and ability to apply knowledge towards
tool development.  Inside this Business Group  The Data Center &
Artificial Intelligence Group (DCAI) is at the heart of Intel’s
transformation from a PC company to a company that runs the cloud and
billions of smart, connected computing devices. The data center is the
underpinning for every data-driven service, from artificial
intelligence to 5G to high-performance computing, and DCG delivers the
products and technologies—spanning software, processors, storage, I/O,
and networking solutions—that fuel cloud, communications, enterprise,
and government data centers around the world.  Posting Statement  All
qualified applicants will receive consideration for employment without
regard to race, color, religion, religious creed, sex, national
origin, ancestry, age, physical or mental disability, medical
condition, genetic information, military and veteran status, marital
status, pregnancy, gender, gender expression, gender identity, sexual
orientation, or any other characteristic protected by local law,
regulation, or ordinance.  Benefits  We offer a total compensation
package that ranks among the best in the industry. It consists of
competitive pay, stock, bonuses, as well as, benefit programs which
include health, retirement, and vacation. Find more information about
all of our Amazing Benefits here.  Working Model  This role will be
eligible for our hybrid work model which allows employees to split
their time between working on-site at their assigned Intel site and
off-site. In certain circumstances the work model may change to
accommodate business needs.

---

## Exploring Semantics with GloVe

In this section, I explore some of the  relational operations with pre-trained GloVe (Global Vectors for Word Representation) embeddings.

In [ ]:
# Load Pre-Trained GloVe Embeddings
glove_vectors = api.load("glove-wiki-gigaword-50")

[==================================================] 100.0% 66.0/66.0MB downloaded

### Vector Arithmetic

Here **two different combinations** of terms using the `most_similar` method with `positive` and `negative` arguments

In [ ]:
result = glove_vectors.most_similar(positive=["engineer", "design"], negative=["software"], topn=5)
for word, similarity_score in result:
    print(f"{similarity_score:.3f} | {word}")

0.743 | architect
0.673 | commissioned
0.630 | sculptor
0.616 | conductor
0.614 | distinguished

In [ ]:
result2 = glove_vectors.most_similar(positive=["data", "technical"], negative=["engineer"], topn=5)
for word, similarity_score in result2:
    print(f"{similarity_score:.3f} | {word}")

0.732 | specific
0.721 | scope
0.710 | analysis
0.704 | assessing
0.700 | evaluating

### Odd One Out

Testing the effectiveness of `glove_vectors.doesnt_match()`

In [ ]:
words1 = ["python", "software", "engineer", "data", "snake"]
glove_vectors.doesnt_match(words1)

'snake'

In [ ]:
words2 = ["pipeline", "design", "workflow", "database", "education"]
glove_vectors.doesnt_match(words2)

'pipeline'

---

## Reflective Analysis Questions

### Question 1

When inspecting the LDA topics, which examples made you feel confident that the model found meaningful clusters, and which examples made you doubt the coherence of certain topics? How might you adjust the modeling process (such as number of topics or preprocessing) to improve coherence?

## Answer (Q1):
After testing with 20 and 30 passes, there was the only result that showed any sort of coherence. Every other one is seemingly a random assortments of different words. Interestingly, in each case the most coherent topics had to do with nursing (see below).

* _(Topic 3 with 10 topics)_
_after testing with 10 and 10 passes._
```
 (3,
  '0.026*"patient" + 0.017*"care" + 0.014*"nursing" + 0.012*"nurse" + 0.006*"hospital" + 0.006*"clinical" + 0.006*"physician" + 0.005*"therapist" + 0.005*"health" + 0.004*"therapy"')
```

* _(Topic 17 with 20 topics)_
_after testing with 20 and 30 passes_
```
 (17,
  '0.010*"nursing" + 0.009*"hospice" + 0.007*"nurse" + 0.005*"liberty" + 0.005*"psychiatric" + 0.004*"caregiver" + 0.004*"compassion" + 0.004*"caring" + 0.003*"counselor" + 0.003*"rehab"')
```

In addition to changing the number of passes, to try and improve it after my first run (which was even worse), I modified the tokenizer to filter out words that were less than 2 characters long (as there were tokens such as "h", "y", "de", etc.). Additionally, I added a filter to remove named entities (`token.ent_iob_`) as there were company names dispersed throughout the topic clusters that did not have any visible logic (i.e. the companies were not co-occurring with vocabulary that matched their given field). One issue of note is that the named entity tags from Spacy do not seem to be fully up to date with the inventory of company names, as there remained numerous instances of NE's for companies in all of the results.

I then tried increasing the number of topics further to 30 given we were dealing with a dataset of thousands of job descriptions for a wide variety of different feilds (see results below). Interestingly, when I ran it with 30 topics and 20 passes, while the results were less of a random grabbag of words that were often totally unrelated, there were none that were quite as coherent as the nursing related clusters above (there was a nursing related cluster, but not quite as much coherent of a vocab)

In [ ]:
# Question 1: LDA Topics
lda_model.print_topics(num_topics=30, num_words=10)

[(0,
  '0.015*"skf" + 0.007*"specimen" + 0.006*"fedex" + 0.005*"autism" + 0.005*"nordstrom" + 0.004*"napa" + 0.004*"ace" + 0.004*"mom" + 0.003*"aba" + 0.003*"seattle"'),
 (1,
  '0.011*"galt" + 0.010*"credit" + 0.007*"sale" + 0.007*"figure" + 0.007*"earning" + 0.007*"saas" + 0.007*"owner" + 0.006*"personal" + 0.006*"membership" + 0.005*"careerstaff"'),
 (2,
  '0.012*"trading" + 0.005*"trader" + 0.004*"ios" + 0.003*"thrivework" + 0.002*"eci" + 0.002*"pcu" + 0.002*"altame" + 0.002*"massage" + 0.002*"quantitative" + 0.002*"hydro"'),
 (3,
  '0.011*"beauty" + 0.007*"trailer" + 0.006*"ulta" + 0.006*"bakery" + 0.005*"req" + 0.005*"tradesman" + 0.003*"hair" + 0.003*"street" + 0.003*"foodservice" + 0.003*"datadog"'),
 (4,
  '0.006*"leasing" + 0.004*"associatesassist" + 0.004*"bayada" + 0.002*"delta" + 0.002*"pierce" + 0.002*"tpm" + 0.002*"gate" + 0.002*"csat" + 0.002*"westside" + 0.002*"mcc"'),
 (5,
  '0.007*"hardware" + 0.006*"coordinator" + 0.006*"chain" + 0.006*"logistic" + 0.005*"troubleshoot" + 0.005*"procurement" + 0.004*"attorney" + 0.004*"civil" + 0.004*"feature" + 0.004*"sql"'),
 (6,
  '0.003*"scm" + 0.003*"tile" + 0.003*"hygienist" + 0.002*"optometrist" + 0.002*"clin" + 0.002*"arrow" + 0.002*"optometry" + 0.001*"ppc" + 0.001*"hallmark" + 0.001*"stone"'),
 (7,
  '0.007*"dentist" + 0.005*"android" + 0.005*"cad" + 0.005*"script" + 0.005*"subcontractor" + 0.005*"receivable" + 0.005*"scrum" + 0.004*"dentistry" + 0.004*"semiconductor" + 0.004*"unix"'),
 (8,
  '0.009*"solomon" + 0.009*"ultrasound" + 0.005*"tiktok" + 0.004*"page" + 0.004*"locum" + 0.003*"manpowergroup" + 0.003*"amerigas" + 0.003*"modernization" + 0.003*"propane" + 0.003*"remodeling"'),
 (9,
  '0.014*"cogent" + 0.007*"mortgage" + 0.006*"fpga" + 0.004*"wsp" + 0.003*"photo" + 0.003*"thrivent" + 0.003*"mercyone" + 0.003*"loan" + 0.003*"rehab" + 0.003*"vaccination"'),
 (10,
  '0.008*"psychiatric" + 0.006*"chef" + 0.006*"est" + 0.006*"ehs" + 0.006*"instructional" + 0.004*"interim" + 0.004*"wfm" + 0.004*"carousel" + 0.004*"marvin" + 0.004*"substance"'),
 (11,
  '0.007*"radiologic" + 0.006*"pct" + 0.005*"roofing" + 0.005*"davita" + 0.005*"dialysis" + 0.004*"baxter" + 0.003*"cheese" + 0.003*"renal" + 0.003*"brief" + 0.003*"interventional"'),
 (12,
  '0.006*"pipe" + 0.004*"poverty" + 0.003*"tennis" + 0.003*"tenant" + 0.003*"cis" + 0.003*"borgen" + 0.003*"metronet" + 0.003*"fiber" + 0.002*"ice" + 0.002*"xcel"'),
 (13,
  '0.007*"apex" + 0.007*"amergis" + 0.006*"albertson" + 0.006*"lion" + 0.006*"maxim" + 0.006*"cox" + 0.005*"westrock" + 0.005*"chipotle" + 0.004*"cnc" + 0.003*"franchisee"'),
 (14,
  '0.007*"actalent" + 0.006*"deli" + 0.006*"securita" + 0.006*"securitas" + 0.005*"bjc" + 0.005*"vigilance" + 0.004*"helpfulness" + 0.004*"honeywell" + 0.003*"var" + 0.003*"asm"'),
 (15,
  '0.006*"autozone" + 0.004*"que" + 0.003*"hyatt" + 0.003*"fun" + 0.003*"dish" + 0.003*"waist" + 0.003*"habit" + 0.003*"suggestion" + 0.003*"cane" + 0.003*"crewmember"'),
 (16,
  '0.006*"liberty" + 0.006*"lpn" + 0.006*"nursing" + 0.004*"wind" + 0.004*"geriatric" + 0.004*"nurse" + 0.004*"stride" + 0.004*"hall" + 0.003*"notifying" + 0.003*"otis"'),
 (17,
  '0.015*"macy" + 0.012*"penske" + 0.009*"trinity" + 0.009*"pvh" + 0.007*"providence" + 0.006*"receptionist" + 0.006*"clerical" + 0.006*"caci" + 0.004*"betterhelp" + 0.004*"logistics"'),
 (18,
  '0.009*"mercy" + 0.006*"dice" + 0.004*"devsecop" + 0.004*"snowflake" + 0.003*"exhibitor" + 0.003*"nyc" + 0.003*"gene" + 0.002*"sandy" + 0.002*"ministry" + 0.002*"ryder"'),
 (19,
  '0.006*"hca" + 0.003*"methodist" + 0.003*"biofire" + 0.003*"bmc" + 0.003*"pharmacist" + 0.003*"wash" + 0.003*"carbon" + 0.002*"telecommunications" + 0.002*"surg" + 0.002*"donor"'),
 (20,
  '0.010*"capital" + 0.009*"agent" + 0.006*"chatbot" + 0.006*"stryker" + 0.006*"teksystem" + 0.004*"refrigeration" + 0.004*"claire" + 0.004*"mount" + 0.004*"tray" + 0.004*"paypal"'),
 (21,
  '0.004*"aldi" + 0.004*"reinsurance" + 0.004*"msl" + 0.003*"correctional" + 0.003*"ride" + 0.003*"unitypoint" + 0.003*"dar" + 0.002*"professor" + 0.002*"jail" + 0.002*"asbestos"'),
 (22,
  '0.008*"cinta" + 0.006*"ecommerce" + 0.005*"app" + 0.005*"venue" + 0.004*"shelter" + 0.004*"kid" + 0.004*"consolidated" + 0.004*"armstaffe" + 0.003*"scripting" + 0.003*"topgolf"'),
 (23,
  '0.004*"patient" + 0.003*"sale" + 0.003*"customer" + 0.003*"care" + 0.003*"project" + 0.003*"client" + 0.003*"store" + 0.002*"product" + 0.002*"business" + 0.002*"design"'),
 (24,
  '0.006*"speech" + 0.005*"aaa" + 0.004*"langone" + 0.004*"cisco" + 0.004*"bluebird" + 0.004*"pathology" + 0.002*"stipend" + 0.002*"pathologist" + 0.002*"cls" + 0.002*"weekson"'),
 (25,
  '0.010*"collision" + 0.009*"caliber" + 0.004*"rpm" + 0.004*"tesla" + 0.003*"staffmark" + 0.003*"graph" + 0.003*"signature" + 0.003*"grooming" + 0.002*"aetna" + 0.002*"maplewood"'),
 (26,
  '0.005*"rail" + 0.004*"cha" + 0.003*"helpdesk" + 0.003*"flyer" + 0.002*"hcm" + 0.002*"revature" + 0.002*"traction" + 0.001*"fieldexperience" + 0.001*"laurel" + 0.001*"tommy"'),
 (27,
  '0.005*"alcon" + 0.005*"substation" + 0.004*"bsa" + 0.004*"gaming" + 0.004*"meta" + 0.004*"sage" + 0.003*"powerback" + 0.003*"shrm" + 0.003*"aml" + 0.003*"creator"'),
 (28,
  '0.010*"hospice" + 0.007*"block" + 0.006*"fire" + 0.005*"counselor" + 0.005*"universal" + 0.005*"united" + 0.004*"citi" + 0.004*"dod" + 0.004*"county" + 0.004*"examination"'),
 (29,
  '0.005*"diy" + 0.005*"salesperson" + 0.005*"medpro" + 0.002*"wiper" + 0.002*"moines" + 0.002*"skillsoperate" + 0.002*"des" + 0.002*"medline" + 0.002*"out" + 0.002*"expose"')]

### Question 2

Try to devise a specific query where TF-IDF and Doc2Vec returned very different top matches. What does this tell you about the difference between lexical similarity (shared words) and semantic similarity (shared meaning)? Include the query with your response.

## Answer 2:
The query `query_q2 = ["developer","information","application","design"]` results in differing results (see cell below). This is clearly due to the fact that Doc2Vec recognizes synonyms and related terms while TF-IDF must match exact terms (or lemmas thereof).

In the TF-IDF results, the top match was in the healthcare field and the other two were in the tech/software development field (which is what the target was actually), whereas in the Doc2Vec, the top 2 results are tech/software development though the 3rd was not.

So neither was perfect, but none of the results were the same (as they were in the original test) and the top result was clearly wrong in the TF-IDF test.

In [ ]:
query_q2 = [
    "developer",
    "information",
    "application",
    "design"
]

#tf-idf
print("TF-IDF")
query_bow_q2 = docs_dict.doc2bow(query_q2)
query_tfidf_q2 = tfidf_model[query_bow_q2]
index_tfidf_q2 = similarities.MatrixSimilarity(tfidf_corpus)
sims_tfidf_q2 = index_tfidf[query_tfidf_q2] # results in np array of scores

sorted_sims_tfidf_q2 = sorted(enumerate(sims_tfidf_q2), key=lambda sim: -sim[1])
for rank in range(3):
  doc_index_q2 = sorted_sims_tfidf_q2[rank][0]
  sim_score_q2 = sorted_sims_tfidf_q2[rank][1]
  print(f"\n\nRank {rank + 1} (Score: {sim_score:.4f}):")
  print("\n".join(textwrap.wrap(job_descriptions[doc_index_q2])))

#Doc2Vec
print("Doc2Vec")
query_vec_q2 = d2v_model.infer_vector(query_q2)
sims_d2v = d2v_model.dv.most_similar([query_vec_q2], topn=3)
for rank, (tag, sim_score) in enumerate(sims_d2v[:3]):
  doc_index = int(tag)
  print(f"\n\nRank {rank + 1} (Score: {sim_score_q2:.4f})")
  print(f"\n".join(textwrap.wrap(job_descriptions[doc_index])))

WARNING:gensim.similarities.docsim:scanning corpus to determine the number of features (consider setting `num_features` explicitly)

TF-IDF


Rank 1 (Score: 0.6766):
Job Descriptions: We are looking for a HealthCare Developer Manager.
You will play a pivotal role in driving the development and
implementation of healthcare web applications, ensuring high-quality
code, and guiding the project's technical direction while also
managing a team of developers.  What you can expect to focus on in
this role:Oversee developers and manage developers' work to ensure it
meets timelines for QE.Gate Keeper for Final Code reviews before
moving stories to QE.Resource should have 10+ Years of experience Gate
Keeper for deployment checklist /code mergers.To be considered for
this role, we would love you to have the following
knowledge/experience:Preferable knowledge of (Provider, Edifecs,
Facets, MDP, HIE) Proficient experience in (Guiding Care, SAP,
Portals, and Dynamics) Experience with agile development methodologies
(e.g., Scrum, Kanban) is preferred.Ability to work independently and
manage multiple priorities in a fast-paced environment   Regards,
Deepak KumarInfinite | Exciting times...infinite possibilities…Tel:
+1- 301-355-7756Email: deepak.kumar@infinite.comWeb site:
www.infinite.com


Rank 2 (Score: 0.6766):
Job Title: Sr. Software EngineerJob Type: ContractDuration:
12monthsLocation: 100% RemotePay Rate: $65 - $80/hr  ****Must
currently reside and work out of one of the following states:  AZ CO
FL IL MI MO NC OR TX WI to work in CST/EST time zones**** **No C2C or
1099 I/C available, must work our W-2** **Must be authorized to work
in the U.S**    Summary The Senior Software Developer works as part of
a team responsible for participating in the design, development, and
testing of healthcare/business related applications and products.
Senior Software Developer primarily focus on more strategic
development projects such as key new features or products. The Sr.
Software developer is expected to identify as a full-stack developer
with a strong focus on front-end development. RequirementsMust have at
least 10+ years of Software Development experience.Participate in the
development of healthcare/business related applications.Be part of a
development team using modern development languages, Relational and
NoSQL databasesMust have experience with backend development with Java
and NoSQL.Strong experience with front end development with React is
required.Experience with HTML5, CSS, and XMLMust have experience with
UI frameworks with strong preference for Felt UI.Experience with
healthcare is highly preferredWork with Product Owners and teams to
drive features and specifications, architecture design,
implementation, and other software development responsibilities.Works
closely with in-house UX team to build out modern, responsive,
intuitive interfaces.Create and update technical documentsProvides
technical mentoring and knowledge sharing to Software
Engineers.Contributes to business requirement definition and use case
design as technical expert.Serves as a go-to person for technical
questions, and provides mentoring and knowledge sharing to other
Software Engineers at all levels. The following benefits are offered
for this position: medical, dental, & vision insurance, short-term
disability, life and AD&D insurance, and a 401(k) retirement plan.


Rank 3 (Score: 0.6766):
It's fun to work in a company where people truly BELIEVE in what
they're doing! We're committed to bringing passion and customer focus
to the business. Fullsteam is a rapidly growing, dynamic, and exciting
private equity-backed software and payments company headquartered in
Auburn, AL. The company was formed in 2018 by a core group of talented
payments and software experts. Fullsteam is quickly expanding its
operations through the acquisition of strategic portfolio companies
that could benefit from our cutting-edge software and payments
platform.  Fullsteam is currently seeking an experienced software
developer to join the payments platform development team. The Senior
Software Developer’s responsibilities will include working within
Fullsteam’s new payment processing platform to design/develop/test new
components and features, perform bug fixes, create automated unit
tests, and perform and respond to code reviews while collaborating and
communicating with the other members of the development team, the
IT/Infrastructure team, upper-level management, portfolio company
developers, and internal users of the platform. Qualifications and
ExpectationsExcited and motivated by a significant role on a fast-
moving team with a responsibility and opportunity to deliver many new
and meaningful features promptly to drive rapid customer
growthBachelor's degree in Computer Science, Software Engineering,
Computer Engineering, or related fieldAt least 5 years of software
development experienceFull stack development skills (UIs, APIs, back-
end processes, and databases)Proficiency with C#, MS SQL, JavaScript,
Visual Studio, MVC, WebAPI, Entity Framework, JSON, Dependency
InjectionDemonstrated ability to design, develop, debug, manually
test, create automated testing for, and maintain applications for high
up-timeSuperior verbal and written communicationKnowledge of and
experience with Secure Application Development PracticesPayment
Processing Industry ExperienceUnderstanding of application
architecture, design patterns, methodologies and best
practicesExperience with relational databases, queries, management,
and optimizations Ability to learn quickly under tight deadlinesMust
be able to work collaboratively, but is self-motived for excellence in
deliverablesCloud Application Development (MS Azure)Agile development
process experienceVersion Control Proficiency (GIT/VSTS)Performance
Tuning Expertise Ability to work Monday-Friday during normal business
hours with a feature team consisting of developers and manual QA team
members to plan, design, and deliver new products, new features,
enhancements, performance improvements, and bug fixes and communicate
using Microsoft Teams, and other collaboration tools, with video and
audio on.Ability to work cross team with platform engineers,
automation QA engineers, performance testing engineers, product
managers, product analysts, and technical managers.Ability to provide
support including being able to respond to being paged by the
FullsteamPay monitoring platform after-hours on a limited basis in a
rotation with other developers. Competitive salary based on
experience, knowledge, skills, and abilities. Fullsteam offers Group
Healthcare, 401(k) match. Candidate must be able to pass a
comprehensive background check required for payments-related
businesses.  Benefit Information:Fullsteam and its Family of Companies
offers a competitive wage as well the following benefits:Major
MedicalDentalVision401k with Company MatchPaid HolidaysPersonal Time
OffEmployer Paid Short Term Disability & AD&DOther employee paid
supplemental insurances offered Physical demands and work
environment:Physical demands: While performing the duties of this job,
the employee is occasionally required to walk; sit; use hands to
finger, handle, or feel objects, tools, or controls; reach with hands
and arms; balance; stoop; talk or hear. Employee must occasionally
lift and/or move up to 15 pounds.  This position can be 100% remote,
on-site or hybrid. The candidate would need to have a suitable work
environment set up as their home office and be comfortable managing
their own schedule in a non-corporate office environment if remote.
EEOC & ADA Statement:Fullsteam and its family of companies provides
equal employment opportunities to all employees and applicants for
employment and prohibits discrimination and harassment of any type
without regard to race, color, religion, age, sex, national origin,
disability status, genetics, protected veteran status, sexual
orientation, gender identity or expression, or any other
characteristic protected by federal, state, or local laws.  Fullsteam
and its family of companies complies with federal and state disability
laws and makes reasonable accommodations for applicants and employees
with disabilities. If reasonable accommodation is needed to
participate in the job application or interview process, to perform
essential job functions, and/or to receive other benefits and
privileges of employment, please contact Fullsteam Human Resources.
This applies to all terms and conditions of employment, including
recruiting, hiring, placement, promotion, termination, layoff, recall,
transfer, leaves of absence, compensation, and training. Final
candidate must be able to pass a background check.
Doc2Vec


Rank 1 (Score: 0.2803)
Must have experience with Solumina Application is strongly
preferred.Strong in architect using enterprise application
servers.Familiar with MOM using technologies such as JMS, ESB, and Web
Services is a plus.familiarity with database programming (PLSQL and
T-SQL) is a plus Job description:10+ Years’ experienceThe Solution
Architect is responsible for the overall solution design and will
provide day-to-day oversight, direction and guidance to the deployment
team, and coordinate with other stakeholders such as Product
Management to successfully deliver solutions.Participate in customer
business requirements sessions and provide expert level requirements
analysis to develop solution specifications.Provide creative solutions
to complex business problems by challenging current ideas and
championing industry best practices.Guide and mentor the project team
through requirements specification, design, development, and
deployment to ensure customer requirements are met.Lead design
workshops to help customers achieve desired outcomes from their
investment.Facilitate business process design and development that
leverages Solumina capabilities.Resolve design challenges to ensure
that the solution is producing the expected results.Work with our
customers to develop a maturity roadmap leveraging the power of
SoluminaWork with Account Executives and Client Partners to articulate
the value of Solumina and our Services solution implementation
methodology.Develop technical documentation and prepare product
demo/presentation materials to validate requirements and ensure user
acceptance.Ensure standards and best practices for project management,
business/system analysis and development are followed.Support the
validation and testing of the solution.Support data management and
data integration related activities. Required skills:Excellent written
and verbal communicationExcellent analysis and process decomposition
skills to solve a variety of problems with complex scope.Experience in
engaging and negotiating with C-level stakeholders.Experience in
manufacturing processes, information systems, application integration,
process re-engineering and system implementation
methodologies.Familiar with cloud computing solutions, architecture,
and security protocolAbility to do domain modeling of business objects
as both Java objects and XML Schema is a plus.Familiar with MOM using
technologies such as JMS, ESB, and Web Services is a plus.Expertise in
JEE development using EJB, JAVA, JMS and Hibernate with knowledge in
three tier architect using enterprise application servers such as
Apache Tomcat, WebSphere, Tibco, Weblogic or Netweaver/PI is a
plusTechnical expertise working with ERP, SQL database tools and
familiarity with database programming (PLSQL and T-SQL) is a
plusExperience with Solumina Application is strongly preferred.


Rank 2 (Score: 0.2803)
Center 3 (19075), United States of America, McLean, VirginiaSoftware
Engineer, Full Stack  Do you love building and pioneering in the
technology space? Do you enjoy solving complex business problems in a
fast-paced, collaborative, inclusive, and iterative delivery
environment? At Capital One, you'll be part of a big group of makers,
breakers, doers and disruptors, who solve real problems and meet real
customer needs. We are seeking Full Stack Software Engineers who are
passionate about marrying data with emerging technologies. As a
Capital One Software Engineer, you’ll have the opportunity to be on
the forefront of driving a major transformation within Capital One.
What You’ll Do:    Collaborate with and across Agile teams to design,
develop, test, implement, and support technical solutions in full-
stack development tools and technologies  Share your passion for
staying on top of tech trends, experimenting with and learning new
technologies, participating in internal & external technology
communities, mentoring other members of the engineering community
Collaborate with digital product managers, and deliver robust cloud-
based solutions that drive powerful experiences to help millions of
Americans achieve financial empowerment  Utilize programming languages
like JavaScript, Java, HTML/CSS, TypeScript, SQL, Python, and Go, Open
Source RDBMS and NoSQL databases, Container Orchestration services
including Docker and Kubernetes, and a variety of AWS tools and
services   Basic Qualifications:    Bachelor’s Degree  At least 2
years of experience in software engineering (Internship experience
does not apply)   Preferred Qualifications:   3+ years of experience
in at least one of the following: JavaScript, Java, TypeScript, SQL,
Python, or Go  1+ years of experience with AWS, GCP, Microsoft Azure,
or another cloud service  2+ years of experience in open source
frameworks  2+ years of experience in Agile practices  Understanding
of API Design  Understanding of scalable and optimized database design
Understanding of cybersecurity best practices  Experience with unit
testing and documentation  Experience communicating with many types
and levels of stakeholders   At this time, Capital One will not
sponsor a new applicant for employment authorization for this
position.  The minimum and maximum full-time annual salaries for this
role are listed below, by location. Please note that this salary
information is solely for candidates hired to perform work within one
of these locations, and refers to the amount Capital One is willing to
pay at the time of this posting. Salaries for part-time roles will be
prorated based upon the agreed upon number of hours to be regularly
worked.  New York City (Hybrid On-Site): $138,500 - $158,100 for
Software Engineer  Candidates hired to work in other locations will be
subject to the pay range associated with that location, and the actual
annualized salary amount offered to any candidate at the time of hire
will be reflected solely in the candidate’s offer letter.  This role
is also eligible to earn performance based incentive compensation,
which may include cash bonus(es) and/or long term incentives (LTI).
Incentives could be discretionary or non discretionary depending on
the plan.  Capital One offers a comprehensive, competitive, and
inclusive set of health, financial and other benefits that support
your total well-being. Learn more at the Capital One Careers website .
Eligibility varies based on full or part-time status, exempt or non-
exempt status, and management level.  This role is expected to accept
applications for a minimum of 5 business days.No agencies please.
Capital One is an equal opportunity employer committed to diversity
and inclusion in the workplace. All qualified applicants will receive
consideration for employment without regard to sex (including
pregnancy, childbirth or related medical conditions), race, color,
age, national origin, religion, disability, genetic information,
marital status, sexual orientation, gender identity, gender
reassignment, citizenship, immigration status, protected veteran
status, or any other basis prohibited under applicable federal, state
or local law. Capital One promotes a drug-free workplace. Capital One
will consider for employment qualified applicants with a criminal
history in a manner consistent with the requirements of applicable
laws regarding criminal background inquiries, including, to the extent
applicable, Article 23-A of the New York Correction Law; San
Francisco, California Police Code Article 49, Sections 4901-4920; New
York City’s Fair Chance Act; Philadelphia’s Fair Criminal Records
Screening Act; and other applicable federal, state, and local laws and
regulations regarding criminal background inquiries.  If you have
visited our website in search of information on employment
opportunities or to apply for a position, and you require an
accommodation, please contact Capital One Recruiting at 1-800-304-9102
or via email at RecruitingAccommodation@capitalone.com . All
information you provide will be kept confidential and will be used
only to the extent required to provide needed reasonable
accommodations.  For technical support or questions about Capital
One's recruiting process, please send an email to
Careers@capitalone.com  Capital One does not provide, endorse nor
guarantee and is not liable for third-party products, services,
educational tools or other information available through this site.
Capital One Financial is made up of several different entities. Please
note that any position posted in Canada is for Capital One Canada, any
position posted in the United Kingdom is for Capital One Europe and
any position posted in the Philippines is for Capital One Philippines
Service Corp. (COPSSC).


Rank 3 (Score: 0.2803)
Job Description  Play a critical role in ensuring the efficient and
accurate distribution of products to customers and stakeholders. You
will aim to meet production targets, maintain product consistency, and
contribute to the overall success of the company by adhering to
quality standards and safety protocols with a leader in medical kit-
production in Columbus, GA. As a Production Specialist, you will be
responsible for maintaining cleanliness and organization within the
production area to ensure a safe and efficient workspace. You will
document and report any non-conformities and collaborate with the
production team to maintain product quality. Apply today to reserve
your path to success with The Reserves Network.  What Matters Most
Competitive pay of $11 an hourTemp-to-hire opportunity with potential
for career growth and stability On-site position located in the
Midland area.Monday-Friday 7:00am-3:30 pm (Weekend Availability)  Your
New Role  As a Production Specialist, you will have a big impact on
producing high-quality medical kits and meeting company goals. You
will monitor production activities to ensure they adhere to quality
standards, safety regulations, and production schedules. You will
maintain accurate records of production activities, including
inventory logs, production reports, and quality control documentation.
What You Need  High school diploma or GED Entry Level Experience.Basic
knowledge of MS Office. The ability to stand for 8-10 hours. Must be
able to pass a pre-employment screening.  Your New Organization  Enjoy
competitive compensation, health, vision, and dental insurance plans,
and a 401(k) plan. Get paid weekly through direct deposit for every
hour you work. When you partner with The Reserves Network, you get to
work with experienced recruiters who will advise you on all aspects of
your job search and career aspirations.  Ready to take control of the
way you work? Complete our application today and join The Reserves
Network team, where your skills and contributions will be valued and
rewarded. Reserve your path to success with The Reserves Network –
apply today.  If you would like additional information, call
706-324-1910  Your Career Partner  Veteran-founded and family-owned,
The Reserves Network specializes in connecting exceptional talent with
rewarding opportunities. With our extensive industry experience, we
are dedicated to helping you achieve your professional goals and shine
in your field. Submit your application for consideration in this and
other positions and gain exclusive access to our mobile app for job
notifications.  As an equal-opportunity employer, we value our

### Question 3

In working with these unsupervised methods, how did the lack of labeled ground truth affect your ability to evaluate which method was "better"? What strategies did you use to judge model quality without explicit labels?

## Answer 3:

Without a ground truth to test against, I relied upon manually checking the clusters and rankings. With regards to the Similarity of job postings to the queries, this was managable because we only chose to check the top 3 results, given there were thousands of posts in the dataset, this would not be reasonable to check all of the rankings this way.

Topic clustering is managable to check manually but there is no scientific way to rate the quality beyond just reading the clusters and deciding which seem to make sense and which don't.

### Question 4

When working with the pre-trained GloVe embeddings, where did they seem to capture intuitive relationships between terms, and where did they break down? What might this suggest about using general-purpose embeddings for specialized domains?

## Answer 4:
For Vector Arithmatic the result for the first try was reasonable (i.e. "architect" is a good possible result for `"engineer", "design" - "software"`), however for the second try (`"data", "technical" - "engineer"`), the results are somewhat nonsensical and none are actual jobs or (Ideally they should've produced a job that requires analysis of data but not an engineer). This may be due to the training data for glove being not from the domain of jobs, but from Wikipedia.

 For Odd-one out: in the example of "`words1`" (below), where all terms are clearly related to tech/software industry with the exception of "snake" that worked very well. However in the second "`words2`" where, "education" seems to be the most likely mis-match, it choses "pipeline". However, in `words2`, it is possible that all of them would belong in some contexts (i.e. software design ***for*** *education*). This shows that the use of `glove_vectors.doesnt_match()` only really works in more obvious cases.

In [ ]:
#  Vector Arithmatic 1
result = glove_vectors.most_similar(positive=["engineer", "design"], negative=["software"], topn=5)
for word, similarity_score in result:
    print(f"{similarity_score:.3f} | {word}")

0.743 | architect
0.673 | commissioned
0.630 | sculptor
0.616 | conductor
0.614 | distinguished

In [ ]:
# Odd-one Out 1
print(words1)
print(glove_vectors.doesnt_match(words1))

['python', 'software', 'engineer', 'data', 'snake']
snake

In [ ]:
#  Vector Arithmatic 2
result2 = glove_vectors.most_similar(positive=["data", "technical"], negative=["engineer"], topn=5)
for word, similarity_score in result2:
    print(f"{similarity_score:.3f} | {word}")

0.732 | specific
0.721 | scope
0.710 | analysis
0.704 | assessing
0.700 | evaluating

In [ ]:
# Odd-one Out 2
print(words2)
print(glove_vectors.doesnt_match(words2))

['pipeline', 'design', 'workflow', 'database', 'education']
pipeline

### Question 5

Imagine you had labeled data for your task (e.g. document categories or relevance scores). How would that change the role of these unsupervised techniques in your workflow? Describe how you might combine unsupervised methods (LDA, embeddings) with supervised models to build a more feature-rich or robust system.

## Answer 5:

Labeled data would enable the training, and subsequent testing of a classifier.  Without the labels, i.e. in unsupervised scenarios, you can only cluster and find patterns in documents, not predict categories for new documents the model hasn't seen.

The vector outputs of LDA, Doc2Vec, and TF-IDF and GloVe could be reused and combined into a single vector then fed into a supervised model such as a Naive Bayes or SVM as feature vector. Doing this, each of these features' shortcomings could be enhanced.

On the document level, LDA only groups vocabulary from all documents in a corpus into *unlabeled*, numbered clusters (i.e. it provides a probability distribution over unlabeled topic clusters for each given document). Since the input of LDA's probabilistic model is based on word counts and co-occurrence (i.e. TF-IDF or Bag of Words input), which do not account for synonyms or alternate phrasing, combining LDA this with Doc2Vec's dense semantic embedding for a document, which is not vocabulary dependent, combining these two features would be beneficial.

Additionally, on the word-level, along the same lines, given that TF-IDF does not capture synonymous language, the TF-IDF for a vocabulary in a given set of documents could be enhanced by combining with GloVe embeddings (as averaged vectors).

### Note to self:
* TODO: combine LDA + Doc2Vec + TF-IDF + GloVe vectors and compare clusters

---

## Notebook Submission

Before submitting:
- Ensure all code cells have been executed and display output
- Verify that all written response cells contain your analysis

See Canvas for additional submission instructions.